<?xml version="1.0"?>

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       name="ud" >

  <xacro:include filename="$(find ubiquitous_display)/urdf/youbot_base_only.urdf.xacro" />

  <!-- Definition of various sizes -->
  <property name="bottom_pillar_height" value="0.1"/>
  <property name="middle_pillar_height" value="0.157"/>
  <property name="top_pillar_height" value="0.435"/>
  <property name="pillar_radius" value="0.01"/>
  <property name="pillar_offset_x" value="0.21"/>
  <property name="pillar_offset_y" value="0.06"/>
  <property name="plate_len_x" value="0.5"/>
  <property name="plate_len_y" value="0.2"/>
  <property name="plate_len_z" value="0.004"/>
  <property name="bar_len_x" value="0.18"/>
  <property name="bar_len_y" value="0.02"/>
  <property name="bar_len_z" value="0.02"/>
  <property name="hokuyo_offset_x" value="0.25"/>
  <property name="hokuyo_offset_z" value="0.037"/>

  <!-- Definition of colors -->
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <!-- Body -->
  <!-- Bottom part -->
  <link name="bottom_pillars_link">
    <visual>
      <geometry>
        <cylinder length="${bottom_pillar_height}" radius="${pillar_radius}"/>
      </geometry>
      <origin xyz="${pillar_offset_x} ${pillar_offset_y} ${bottom_pillar_height/2}"/>
      <material name="black"/>
    </visual>
    <visual>
      <geometry>
        <cylinder length="${bottom_pillar_height}" radius="${pillar_radius}"/>
      </geometry>
      <origin xyz="-${pillar_offset_x} ${pillar_offset_y} ${bottom_pillar_height/2}"/>
      <material name="black"/>
    </visual>
    <visual>
      <geometry>
        <cylinder length="${bottom_pillar_height}" radius="${pillar_radius}"/>
      </geometry>
      <origin xyz="${pillar_offset_x} -${pillar_offset_y} ${bottom_pillar_height/2}"/>
      <material name="black"/>
    </visual>
    <visual>
      <geometry>
        <cylinder length="${bottom_pillar_height}" radius="${pillar_radius}"/>
      </geometry>
      <origin xyz="-${pillar_offset_x} -${pillar_offset_y} ${bottom_pillar_height/2}"/>
      <material name="black"/>
    </visual>
  </link>
  <joint name="base_to_bottom_pillars_joint" type="fixed">
    <parent link="base_link"/>
    <child link="bottom_pillars_link"/>
  </joint>

  <link name="bottom_plate_link">
    <visual>
      <geometry>
        <box size="${plate_len_x} ${plate_len_y} ${plate_len_z}"/>
      </geometry>
      <origin xyz="0 0 -${plate_len_z/2}"/>
      <material name="white"/>
    </visual>
    <visual>
      <geometry>
        <box size="${bar_len_x} ${bar_len_y} ${bar_len_z}"/>
      </geometry>
      <origin xyz="0.20 0.025 ${bar_len_z/2}"/>
     <material name="gray" />
    </visual>
    <visual>
      <geometry>
        <box size="${bar_len_x} ${bar_len_y} ${bar_len_z}"/>
      </geometry>
      <origin xyz="0.20 -0.025 ${bar_len_z/2}"/>
     <material name="gray" />
    </visual>
    <visual>
      <geometry>
        <box size="${bar_len_x} ${bar_len_y} ${bar_len_z}"/>
      </geometry>
      <origin xyz="-0.20 0.025 ${bar_len_z/2}"/>
     <material name="gray" />
    </visual>
    <visual>
      <geometry>
        <box size="${bar_len_x} ${bar_len_y} ${bar_len_z}"/>
      </geometry>
      <origin xyz="-0.20 0.025 ${bar_len_z/2}"/>
     <material name="gray" />
    </visual>
    <visual>
      <geometry>
        <box size="${bar_len_x} ${bar_len_y} ${bar_len_z}"/>
      </geometry>
      <origin xyz="-0.20 -0.025 ${bar_len_z/2}"/>
     <material name="gray" />
    </visual>
  </link>
  <joint name="bottom_pillars_to_bottom_plate_joint" type="fixed">
    <parent link="bottom_pillars_link"/>
    <child link="bottom_plate_link"/>
    <origin xyz="0 0 ${bottom_pillar_height}"/>
  </joint>

 <!-- Middle part -->
  <link name="middle_pillars_link">
    <visual>
      <geometry>
        <cylinder length="${middle_pillar_height}" radius="${pillar_radius}"/>
      </geometry>
      <origin xyz="${pillar_offset_x} ${pillar_offset_y} ${middle_pillar_height/2}"/>
      <material name="black"/>
    </visual>
    <visual>
      <geometry>
        <cylinder length="${middle_pillar_height}" radius="${pillar_radius}"/>
      </geometry>
      <origin xyz="-${pillar_offset_x} ${pillar_offset_y} ${middle_pillar_height/2}"/>
      <material name="black"/>
    </visual>
    <visual>
      <geometry>
        <cylinder length="${middle_pillar_height}" radius="${pillar_radius}"/>
      </geometry>
      <origin xyz="${pillar_offset_x} -${pillar_offset_y} ${middle_pillar_height/2}"/>
      <material name="black"/>
    </visual>
    <visual>
      <geometry>
        <cylinder length="${middle_pillar_height}" radius="${pillar_radius}"/>
      </geometry>
      <origin xyz="-${pillar_offset_x} -${pillar_offset_y} ${middle_pillar_height/2}"/>
      <material name="black"/>
    </visual>
  </link>
  <joint name="bottom_plate_to_middle_pillars_joint" type="fixed">
    <parent link="bottom_plate_link"/>
    <child link="middle_pillars_link"/>
  </joint>

  <link name="middle_plate_link">
    <visual>
      <geometry>
        <box size="${plate_len_x} ${plate_len_y} ${plate_len_z}"/>
      </geometry>
      <origin xyz="0 0 -${plate_len_z/2}"/>
      <material name="white"/>
    </visual>
  </link>
  <joint name="bottom_plate_to_middle_plate_joint" type="fixed">
    <parent link="bottom_plate_link"/>
    <child link="middle_plate_link"/>
    <origin xyz="0 0 ${middle_pillar_height}"/>
  </joint>

  <!-- Top part -->
  <link name="top_pillars_link">
    <visual>
      <geometry>
        <cylinder length="${top_pillar_height}" radius="${pillar_radius}"/>
      </geometry>
      <origin xyz="${pillar_offset_x} ${pillar_offset_y} ${top_pillar_height/2}"/>
      <material name="black"/>
    </visual>
    <visual>
      <geometry>
        <cylinder length="${top_pillar_height}" radius="${pillar_radius}"/>
      </geometry>
      <origin xyz="-${pillar_offset_x} ${pillar_offset_y} ${top_pillar_height/2}"/>
      <material name="black"/>
    </visual>
    <visual>
      <geometry>
        <cylinder length="${top_pillar_height}" radius="${pillar_radius}"/>
      </geometry>
      <origin xyz="${pillar_offset_x} -${pillar_offset_y} ${top_pillar_height/2}"/>
      <material name="black"/>
    </visual>
    <visual>
      <geometry>
        <cylinder length="${top_pillar_height}" radius="${pillar_radius}"/>
      </geometry>
      <origin xyz="-${pillar_offset_x} -${pillar_offset_y} ${top_pillar_height/2}"/>
      <material name="black"/>
    </visual>
  </link>
  <joint name="middle_plate_to_top_pillars_joint" type="fixed">
    <parent link="middle_plate_link"/>
    <child link="top_pillars_link"/>
  </joint>

  <link name="top_plate_link">
    <visual>
      <geometry>
        <box size="${plate_len_x} ${plate_len_y} ${plate_len_z}"/>
      </geometry>
      <origin xyz="0 0 -${plate_len_z/2}"/>
      <material name="white"/>
    </visual>
  </link>
  <joint name="top_pillars_to_top_plate_joint" type="fixed">
    <parent link="top_pillars_link"/>
    <child link="top_plate_link"/>
    <origin xyz="0 0 ${top_pillar_height}"/>
  </joint>

  <!-- base laser front -->
  <xacro:hokuyo_urg04_laser name="base_laser_front" parent="bottom_plate" ros_topic="base_scan" update_rate="10" min_angle="-1.57" max_angle="1.57">
    <origin xyz="${hokuyo_offset_x} 0 ${hokuyo_offset_z}" rpy="0 0 0"/>
  </xacro:hokuyo_urg04_laser>
</robot>
